server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - JwtAuthFilter
      routes:
        - id: auth-service
          uri: http://localhost:8086
          predicates:
            - Path=/auth/**
          filters:
            - name: JwtAuthFilter
              args:
                publicPath: /auth/login
        - id: employee-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/employees/**
          filters:
            - StripPrefix=1
        - id: payroll-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/payroll/**
          filters:
            - StripPrefix=1
        - id: attendance-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/attendance/**
          filters:
            - StripPrefix=1
        - id: notification-service-email
          uri: http://localhost:8084
          predicates:
            - Path=/api/send-email
          filters:
            - StripPrefix=1
        - id: notification-service-sms
          uri: http://localhost:8084
          predicates:
            - Path=/api/send-sms
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
