server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - JwtAuthFilter
      routes:
        - id: auth-service
          uri: http://localhost:8086
          predicates:
            - Path=/auth/login
          filters:
            - name: JwtAuthFilter
              args:
                publicPath: true
        - id: tibco-bw
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
        - id: employee-service
          uri: http://localhost:8081
          predicates:
            - Path=/employees/**
        - id: payroll-service
          uri: http://localhost:8082
          predicates:
            - Path=/payroll/**
        - id: attendance-service
          uri: http://localhost:8083
          predicates:
            - Path=/attendance/**
        - id: notification-service-email
          uri: http://localhost:8084
          predicates:
            - Path=/send-email
        - id: notification-service-sms
          uri: http://localhost:8084
          predicates:
            - Path=/send-sms

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
